### ISSUE TITLE
UI doesn't switch to Mobile view when resized low enough

### ISSUE THREAD

**Issue by Amrykid** [Mordonus/MALClient#12]
The UI should switch to the mobile view when you resize the window low enough. Otherwise, the anime info pane overlaps the anime list.
![mal](https://cloud.githubusercontent.com/assets/251501/14820389/0d2bc8de-0b8c-11e6-9a78-8f5f5cbee0b6.PNG)

**Comment by Mordonus** [comment]
This works as intended right now. Mobile and desktop views are so much different that it would take much more time to merge than it's worth imo. I may remove this minimum width value for items grid.

**Comment by Amrykid** [comment]
Do you accept pull requests? Shouldn't be too hard with the RelativePanel.

**Comment by Mordonus** [comment]
If it's going to work better , sure thing :)

**Comment by Amrykid** [comment]
Heh, you weren't kidding about the UIs being extremely different. I am gonna have to recreate the UI. :'(

**Comment by Mordonus** [comment]
Yeah, it's because of this splitter thingy. ^^

**Comment by Amrykid** [comment]
This issue still bothers me a bit. I feel like you're doubling work for yourself by maintaining two branches. I will still submit a PR in the future to help out a bit.

**Comment by Mordonus** [comment]
Yeah, it's a bit troublesome but combining this into one view would require tons of work too. I'm planning to put this into one branch with some shared resources but I can't get myself to do that :)

**Comment by Amrykid** [comment]
I'll throw up a PR now just to get the ball rolling. It'll be a while before I can get things going.
