### ISSUE TITLE
Where did the option to pin custom tiles go?

### ISSUE THREAD

**Issue by Insanitylious** [Mordonus/MALClient#13]
I  don't know of you removed it in a update, but it just disappeared. I would like to pin a tile, just like the MAL url one, but that directs me to another website, example: KissAnime. I liked it, cause it gave me a nice look on the tile instead of that blue Edge tile.

**Comment by Insanitylious** [comment]
For clarification: Anime tile, with custom URL

**Comment by Mordonus** [comment]
It's only available on "list/detailed grid" view. When I redo tiles I will overhaul this too.

**Comment by Insanitylious** [comment]
I can't seem to find it :/

**Comment by Mordonus** [comment]
![wp_ss_20160429_0001](https://cloud.githubusercontent.com/assets/6102530/14918283/4f897732-0e23-11e6-9de8-ad5e4dd0160b.png)

**Comment by Insanitylious** [comment]
I'm stupid. The tree dots weren't clearly visible for me. I'm sorry.

**Comment by Mordonus** [comment]
Hah , no problem! Glad to help :)
