### ISSUE TITLE
[Mobile][Lumia950]App crash (not logged in)

### ISSUE THREAD

**Issue by Thystro** [Mordonus/MALClient#16]
The app crashes when going to seasonal anime and not being logged in.
This works fine on the website itself, the app does not like it to much.

When you log in and log out again it is no problem to access seasonal anime.

**Comment by Mordonus** [comment]
Ugh, I keep forgetting to test how things work when logged out. Thanks for report! 

There's an update in certification right now so I'll fix this in next one.

**Comment by Thystro** [comment]
Good to hear!
I will update my review after the update :)

**Comment by Mordonus** [comment]
Actually I have this already fixed as I had to cancel certification in order fill in something :)
I'll be pushing this to certification in next few hours ^^

**Comment by Mordonus** [comment]
Packages pushed to the store. It will take MSFT a few hours to deliver.

**Comment by Mordonus** [comment]
They sure take their time ;d

**Comment by Mordonus** [comment]
And how are things?

**Comment by Thystro** [comment]
Give it a try. works like a charm. 
I've updated the review to support you and also made a little beer donation to you ;)

Keep it up, i like developers that work actively with the community!
