### ISSUE TITLE
Little update/refresh bug?

### ISSUE THREAD

**Issue by kn1000a** [Mordonus/MALClient#17]
I think I found a bug where when you open the app (logged in), you're show the list of anime you're watching but the anime tiles don't have a weekly release day specified or the current ratings. Like this screenshot here:

![wp_ss_20160502_0009](https://cloud.githubusercontent.com/assets/19158085/14969928/f7f9bb7c-1079-11e6-9aa4-f35353399cc2.png)

I have to click on the anime (only a one time thing it seems) then when I pressed back or quit out of the app, the data is now visible:

![wp_ss_20160502_0012](https://cloud.githubusercontent.com/assets/19158085/14969970/558c2df6-107a-11e6-9f11-7ec8a493cff0.png)

I think this is only a problem if we add anime through other clients or on the website itself, and if it is through this app all is fine. Still, it was just a small bug, just letting you know.

Also a small question: Are these anime weekly release time Japan-based or U.S.? Some are way far off what I thought were release dates, for example the current Concrete Revolutio S2 come out every Friday, but on here it said Sunday?

And thank you for making such an awesome app :)

**Comment by Mordonus** [comment]
Mal does not return airing time or overall score in library data so I'm populating it as soon as I get it from details/seasonal/top. Once details are opened data gets cached and it populates when needed. Making bazillions of additional requests for each entry is pointless, especially when you cannot fetch data about specific anime but you have to search by title and filter results list...

I'm parsing the date which mal returns in yyyy-mm-dd format. I have no clue what it exactly represents as there's no documentation about this and btw Mal api is just very bad ^^

Unless Mal releases better api this is how things will work :(

**Comment by Mordonus** [comment]
Adding air day offset may be helpful here though. :D

**Comment by kn1000a** [comment]
It's alright, thank you for making the awesome app! If MAL have any plans for an app they would've care more about the API, but with what's available you've done an exceptional job 👍
