### ISSUE TITLE
[Big!] Hummingbird support!

### ISSUE THREAD

**Issue by Mordonus** [Mordonus/MALClient#18]
Because some lone soul requested Hummingbird support in reddit thread I decided to add it :D
And it's almost done (at least on basic functionality level). Their API is better but provides less information than I'd like to. Right now I have adapted as much as I could to current app. 
Things missing:

* Profile page - they only give favourite anime + random stuff like avatar,name etc so skipped for now.
* Manga library is read only and there's no details because there's *no* manga support whatsoever.
* Proper logo/splashscreen image. I have done some placeholders with hummingbird in the background but I probably can do better.
* Various details weren't "ported" to hummingbird yet. If somebody could do list off those missing thing I'd be grateful (stuff like buttons in details page/ obsolote settings).
* Some old bugs ;d

New things:
* New profile page ofc.
* List caching now works properly and is enabled by default.
* A bit of optimizations, reduced amount of doubled data.
* Cleaned up code from like 1st day of development.

If you would like to test this thing out just to check whether MAL works as it should or maybe you want to jump ships to hummingbird there's x64 package below. If somebody wants x86 feel free to write here.

**Download v4.0.3.0 x64**
https://onedrive.live.com/redir?resid=C8FF5587AF40716D!222772&authkey=!ALxzRmgZnet5zsI&ithint=file%2crar
**Download v4.0.3.0 ARM**
https://onedrive.live.com/redir?resid=C8FF5587AF40716D!222771&authkey=!ACRbeXQxiDAV6rY&ithint=file%2crar

You can install this thing by running PowerShell script include or via device portal in case of arm.

**Comment by Mordonus** [comment]
Hummingbird api seems to return unexpected values for some series and app may crash when building library. Fix later today.

**Comment by denaxin** [comment]
Sorry, for unrelated comment, but are you still interested in the new Logo/name? :)

**Comment by Mordonus** [comment]
Yup, currently I have sth like this:
![image](https://cloud.githubusercontent.com/assets/6102530/15053307/414576f6-1302-11e6-82a9-04d66394bea7.png)

It's quite related to be honest :D

**Comment by Mordonus** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/15083896/354c7196-13d0-11e6-92c4-8ccb477a13e9.png)
Thoughts?

**Comment by Mordonus** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/15090508/3979c46c-142a-11e6-9c95-ff59774362d0.png)

**Comment by Mordonus** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/15090612/c152d948-142d-11e6-9b61-d157f937d4cf.png)
Looks good imo.

**Comment by Mordonus** [comment]
New builds! v4.0.3.0 for ARM and x64!

**Comment by Mordonus** [comment]
Update v4.0.4.0 just went to certification!

It's BIG and while I was testing it extensively we all know that some bugs will go unnoticed, so please report should you find something :)

**Comment by Mordonus** [comment]
Found a few bugs in v4.0.4.0, nothing big but I had to cancel submission. I'll upload fixed packages later today.

**Comment by Mordonus** [comment]
v4.0.5.0 just went to certification it will take a day or 2 for MSFT to deliver.
