### ISSUE TITLE
[BUG & Suggestion]

### ISSUE THREAD

**Issue by luzankia** [Mordonus/MALClient#19]
Hello,
First, I think this app is great enough to gain a support (so I did).

Here a little bug :
If I add a new series and directly edit "my watched episodes" the popup that offer me the option to switch from "plan to watch" to "Watching" (great idea) come.
![2016-05-04 23_00_12-malclient](https://cloud.githubusercontent.com/assets/19195349/15029174/bce4250c-124c-11e6-9b15-8fed53697e69.png)
When I click "yes" this popup come : 
![2016-05-04 23_00_28-malclient](https://cloud.githubusercontent.com/assets/19195349/15029214/e8a479bc-124c-11e6-8e50-7ce920b7fd82.png)

As for the suggestion, I think you should replace the "X" button for removing a series from the collection by a Bin or something alike.

My written English is somewhat rusted, sorry.

**Comment by Mordonus** [comment]
Hmm, I'm not getting this error... Was it onetime only or does it still occur?

Good idea with this bin icon, I forgot about it :)

**Comment by luzankia** [comment]
It append every time on my Pc and tablet, both with the last update (non beta) of Windows 10.
In video or manga alike.

**Comment by Mordonus** [comment]
Okay, I'll investigate once I'm home :)

**Comment by Mordonus** [comment]
I'm unable to reproduce this on both beta build and production one. Can anyone confirm this?

**Comment by Mordonus** [comment]
Okay, I'm just blind...

Fixed this + increment button + bin button in v4.0.2.0+
