### ISSUE TITLE
[Question] Is this ad button in hamburger menu working?

### ISSUE THREAD

**Issue by Mordonus** [Mordonus/MALClient#21]
I'm getting info that there are requests for ads and nothing else. It looks like Microsoft is unable to serve any ads... Did somebody managed to watch one?

**Comment by ZeroOmar** [comment]
no, I got the same 

![screenshot 68](https://cloud.githubusercontent.com/assets/18592104/15181215/398e4838-1786-11e6-8ba9-4b80c0221a67.png)

**Comment by Mordonus** [comment]
Where are you from?

**Comment by ZeroOmar** [comment]
Egypt

**Comment by Mordonus** [comment]
As far as I know (from MS support) biggest ad catalog is available in US/UK/Germany/Spain etc. Can anyone from those countries confirm this?

**Comment by Mordonus** [comment]
I'll be switching ad provider as microsoft can't even.
