### ISSUE TITLE
Calendar & Tiles -> Next update

### ISSUE THREAD

**Issue by Mordonus** [Mordonus/MALClient#22]
This week comes to an end... thank god!

Next update (which will probably go live next week depending on how my assignment goes) is going to feature:
* Calendar
 * Simple breakdown of airing/planned anime by day.
![image](https://cloud.githubusercontent.com/assets/6102530/15258266/e68f5250-194a-11e6-9dff-b9b1d72e96ce.png)
* Live Tiles
 * I have them working but I don't have screenshot and I don't want to switch branch now xd. They basically have 2 "sides" - one with image and second with title status and watched episodes + you can set url for them just like before. Sync mechanism and UI revamp is still waiting for its turn though. 
* Probably working "support me button" ;d
 * Microsoft has literally no ads as it seems so I'm jumping ships to different provider, who knows how it'll work.

My question is: What do you want to add to Calendar and/or tiles?

**Comment by Mordonus** [comment]
WIP Popup window with tile pinning:
![image](https://cloud.githubusercontent.com/assets/6102530/15268489/9d92868a-19e0-11e6-925f-2dee2c4d6fe8.png)

**Comment by ZeroOmar** [comment]
is the live tile tile option only for pining certain anime to the start screen ? not for the main app ?

if not
The main app live tile should show the "MALClient" icon on one side and the other side shows the profile status like number of watched, completed anime or recent activity or upcoming anime

when you get that support me button working I'll support you every day ^_^

**Comment by Mordonus** [comment]
Right now I'm planning to release tiles for single anime series after this weekend.

I gotta have something to work on for next update, right? ^^
(app tile + more search filters are planned + maybe new telemetry... I'm running out of stuff to do...)

With tiles update this button should work as I've ditched Microdoft "ads" and used different provider, we will see how this works soon enough :)

**Comment by Mordonus** [comment]
One more thing 
![wp_ss_20160521_0001](https://cloud.githubusercontent.com/assets/6102530/15447218/9652120a-1f3a-11e6-8801-79cc2a4e5da6.png)

Swipe to increment/decrement, gonna be useful imo :)

**Comment by ZeroOmar** [comment]
yes, very useful

and one more thing:
can you show the reload button in the bottom bar instead of behind the 3 dot menu ? 
so it will be 1 click to reload instead of 2 clicks

**Comment by Mordonus** [comment]
Probably, but I don't know how will this command bar behave when there's not enough space... brb ^^

**Comment by ZeroOmar** [comment]
it can fit up to 5 icons like dropbox 
and my phone have a low resolution so it should be fine
![wp_ss_20160521_0001](https://cloud.githubusercontent.com/assets/18592104/15447780/b8952394-1f4d-11e6-85f9-94d83aef6fa3.png)

**Comment by Mordonus** [comment]
I'll enable it on library and top pages, seasonal will have calendar icon instead... just in case xd

And with that mobile update is completed.

**Comment by Mordonus** [comment]
Would you like to test those upcoming build so I won't have to worry too much? ^^

**Comment by ZeroOmar** [comment]
yeah sure

**Comment by Mordonus** [comment]
Okay, I'll upload something tommorow :)

**Comment by Mordonus** [comment]
So, preview versions for 4.1.16.0:
Mobile:
https://onedrive.live.com/redir?resid=C8FF5587AF40716D!253418&authkey=!AAbbQ283aNwLSDM&ithint=file%2crar
Desktop x64:
https://onedrive.live.com/redir?resid=C8FF5587AF40716D!253419&authkey=!AD-y-VWFw_3dTAo&ithint=file%2crar

Desktop one can be installed via PowerShell script inside, Mobile one through device portal (Settings->For developers).

They seem to work... "works on my machine" badge kind of thing. Try to break it :D

**Comment by ZeroOmar** [comment]
I've tested both versions
here is the results:

## Mobile version:
- swipe to increment/decrement .............works fine
- calendar page ...................................works fine
- Live tiles............................................works fine
- support me button .............................The video ad works but when I close the video, it keeps looping and the only way to stop it is to force close the app ( Edit: ignored :smile: )

## Desktop Version:
- calendar page ...................................works fine
- Live tiles............................................works fine but when using wide tile the image stretches for a sec then the tile updates (not considred a problem)
- The reload button...............................not showing in the action bar like the mobile version
- support me button .............................crashes the app

**Comment by Mordonus** [comment]
Thanks a lot!

This delayed update thing with tiles is unavoidable, it's just how things work. 
Oh, why do I even hide those buttons in desktop version in the first place?
Desktop support button is "repaired", ads won't work on desktop.

**Comment by Mordonus** [comment]
And off they went to certification!

**Comment by Mordonus** [comment]
Ehh, there are problems with ads in production... again. If they won't work now I'll ditch them altogether. Let me know how they perform.

**Comment by Mordonus** [comment]
Update has just passed certification, should be available shortly. :)
