### ISSUE TITLE
Is Desktop version stable? 

### ISSUE THREAD

**Issue by Mordonus** [Mordonus/MALClient#25]
I'm encountering some odd crashes with extremely odd internal exceptions... Can anyone else relate?

**Comment by ZeroOmar** [comment]
It is working fine for me.
both Desktop and mobile version are stable
I tried to crash it but it didn't :smile:

**Comment by Mordonus** [comment]
Did you put some stress on them? Like switching list/top/seasonal for a while?

**Comment by ZeroOmar** [comment]
once they load switching is fine
but switching when seasonal anime or recommendations are still loading, it craches

**Comment by Mordonus** [comment]
I'm frantically searching for solution, and while I've already applied myriad of fixes this still seems to be a thing...

**Comment by Mordonus** [comment]
Good news... after hours of debugging and searching through internet I did manage to pinpoint the source. One could have thought that loading tons of entries representing anime items would be prone tp failure here... NOPE. It is one mere pivot used for filters... I'm angry...

**Comment by ZeroOmar** [comment]
good news indeed ^_^

**Comment by Mordonus** [comment]
Okay, I still have no clue why this happened... but with next update you will be able to spam change views and filters and app should not crash :D

Now I'll choose some light stuff from TODO list for today's update :)
