### ISSUE TITLE
ideas for future updates

### ISSUE THREAD

**Issue by ZeroOmar** [Mordonus/MALClient#26]
In an earlier thread you said you were running out of stuff to do
So...
I have some ideas for future updates to make it a full featured MALClient :wink: 

## Common:
- Friend list with ability to visit friends profiles
- MAL notifications like new comments, friend requests
- Messages inbox
- Profile stats to show Total number of Entries, number of Rewatched, total number of Episodes, mean score
- Show more info about the user like gender, location, joined date, birthday
- Different accent colors for watching, completed, plan to watch, on hold, dropped (same colors as the site)
- Live tile (we talked about earlier)

## Desktop only:
- Vertical reviews and recommendations like the mobile version
![wp_ss_20160524_0001](https://cloud.githubusercontent.com/assets/18592104/15519256/e59a1952-2200-11e6-84f6-f46ed02188be.jpg)
- Revamped profile page to make use of the large screen state (shows all the info in one page. no taps)
- Swipe to increment/decrement for tablet users ( I don't have a tablet :/ )

	
**These are just ideas so it's totally up to you if you want to make them**

**Comment by Mordonus** [comment]
- Friends and profile revamp -> can do
- Notifs, messages -> can't do (no API)
- More stats -> I'll think about it
- I'll try to fit mal's profile into hummingbird profile page
- Colors -> this may be a little tricky but I'll try

- Again, mal page like hummingbird one.
- Swipe shouldn't be much of an issue.

That being said, It's extremely hectic in my university right now and I have little to no free time right now... I'm thinking about pushing small updates but more frequently now.

**Comment by Mordonus** [comment]
- [x] Added swipe to desktop version.
- [x] Added option to switch between list view and pivot in recommendations and reviews tabs.

This will go live with 4.1.22.0 hopefully, alongside with myriad of optimisations.

**Comment by ZeroOmar** [comment]
Thank you very much for your hard work :+1: 
I'll do my best to support you and will recommend your app to all my anime watching friends

**Comment by Mordonus** [comment]
v4.1.22.0 preview
https://onedrive.live.com/redir?resid=C8FF5587AF40716D!258445&authkey=!ADKnfz7sMMIoAD8&ithint=file%2crar

I have to upload this by this evening if I want to make it in time before weekend. 

Mobile version may come later because there are no critical issues there, there's little time and it's rather pure optimisation for desktop build + some little tweaks...

**Comment by ZeroOmar** [comment]
- Crashes are Fixed
- All the other additions are working fine
-  Remember the bug that I had where the first 10 elements only appeared and it got fixed in build 3.4.48.0 where the rest loads while scrolling. now it's totally fixed all the elements appear without the need to scroll ^_^

**Comment by Mordonus** [comment]
Those items will be incrementally loaded, I just increased initial value to avoid reloading ^^

**Comment by Mordonus** [comment]
Moved to "todo list" issue
