### ISSUE TITLE
Desktop back navigation button.

### ISSUE THREAD

**Issue by Mordonus** [Mordonus/MALClient#30]
Okay, I quite dislike how this thing presents but I'm clueless  on how to make it look better. Any ideas? :D 

![image](https://cloud.githubusercontent.com/assets/6102530/15788632/bd554168-29c8-11e6-8fa4-82cefa45b1cd.png)

**Comment by Mordonus** [comment]
Better? Worse?

![image](https://cloud.githubusercontent.com/assets/6102530/15789385/29ddf278-29cc-11e6-8d21-38b248959686.png)

**Comment by ZeroOmar** [comment]
better
