### ISSUE TITLE
Does not show pictures 

### ISSUE THREAD

**Issue by Katsuga50** [Mordonus/MALClient#32]
![image](https://cloud.githubusercontent.com/assets/19756597/15803607/dd80e97e-2b03-11e6-9a4e-44eb705d89e8.png)

And also when i click on " watch ads" from support option then it does not show ads.

**Comment by Mordonus** [comment]
I'm aware of this bug, (I've written about it in news). MAL has changed html structure a bit and it reads wrong thing. It's already fixed in current builds which will be available on Monday.

**Comment by Mordonus** [comment]
Update now in certification.

**Comment by Mordonus** [comment]
Update on the store :)
