### ISSUE TITLE
[Update 11.06] v4.3.17.0 preview - Articles&News + TopCategories x64+ARM

### ISSUE THREAD

**Issue by Mordonus** [Mordonus/MALClient#33]
Update 11.06.2016

Hello!

Next preview version:
* Articles & News
* Top anime categories
* Hamburger menu now looks a bit better
* Setting to ensure selected item is visible after closing pane.

I feel that this almost everything I'll release next week.
 x64 :
https://onedrive.live.com/redir?resid=C8FF5587AF40716D!269457&authkey=!AB_IZN8fHhBTcdQ&ithint=file%2crar
ARM:
https://onedrive.live.com/redir?resid=C8FF5587AF40716D!269458&authkey=!AK9mQzN8KeKlTzg&ithint=file%2crar

What settings would you like to see for articles?

**Comment by ZeroOmar** [comment]
- articles doesn't load pictures
![screenshot 91](https://cloud.githubusercontent.com/assets/18592104/15879041/a6d76032-2d20-11e6-8de9-47edc3c09bb1.png)
- if I select articles then news the app crashes, opening the news first prevents this crash

**Comment by Mordonus** [comment]
Wut... It was fully working for me. 
Try reloading top anime, maybe you have cached version before html fix.

**Comment by Mordonus** [comment]
Ah, they have changed html today :D

**Comment by Mordonus** [comment]
Okay, I've been fighting with today's updates v4.2.6.0 and v4.2.7.0 (Mobile is a bit delayed), so no update here today as I'm tired ^^. Both of them are now in certification with mostly tweaks, responses to html changes and bugfixes.

**Comment by Mordonus** [comment]
Package has been updated to v4.3.16.0

**Comment by ZeroOmar** [comment]
sorry for being late
all the bugs from v4.3.15.0 are now fixed for me on v4.3.16.0 
:+1: :+1: :+1:

**Comment by Mordonus** [comment]
Good to hear, I'm copy/pasting this to mobile now. Update should arrive next week.

**Comment by Mordonus** [comment]
Changelog:
Update should go live on Monday/Tuesday.


> 14.06.2016 - v4.3.18.0 - Desktop&Mobile Quite big!
> Added News page.
> Added Articles page.
> Added new 7 top anime categories.
> Calendar should no longer crash.
> 
> Mobile:
> Navigating back to anime/manga list from details should now scroll back to selected item more reliably.
> Fixed rare issues with anime update.
> 
> Desktop:
> Proper back navigation for profile.
> New setting that will perform scroll to selected item when closing details pane.
> Hamburger menu expandable buttons got visual upgrade.
> Collapsed hamburger will now look a bit more sensible with expandable sections hidden and replaced with flyouts(right click to show).

**Comment by Mordonus** [comment]
Aaaand it went to certification!
