### ISSUE TITLE
Calender 

### ISSUE THREAD

**Issue by Draegon-McKnight** [Mordonus/MALClient#34]
When I try to open the Calendar within the app it crashes and i have to restart the app. Am I the only one with this issue? I just want to know if I'm doing something wrong

**Comment by Mordonus** [comment]
It's a bug and I'm searching for its source. Could you please provide me with your MAL username?

**Comment by Draegon-McKnight** [comment]
[animelist_1465668150_-_4715492.xml.gz](https://github.com/Mordonus/MALClient/files/310408/animelist_1465668150_-_4715492.xml.gz)
Is this fine or was it something else

**Comment by Mordonus** [comment]
Yeah, this should do the trick :) Thanks!

**Comment by Mordonus** [comment]
Okay, there was literally 1 entry out of 190 that had missing data... thanks MAL ;d

**Comment by Mordonus** [comment]
Fixed e7ed06b

**Comment by Draegon-McKnight** [comment]
thank you so i should be able to open it now

**Comment by Draegon-McKnight** [comment]
or when it next updates

**Comment by Mordonus** [comment]
If you download current preview it should work now, otherwise you will have to wait for update on the store.

**Comment by Draegon-McKnight** [comment]
Thank you
