### ISSUE TITLE
Add "unranked" option to "My score" choice list.

### ISSUE THREAD

**Issue by kureijienjeru666** [Mordonus/MALClient#36]
It's really annoying, that when I need to delete my score for title, I must use web version. Can u improve that? Thx a lot.

**Comment by Mordonus** [comment]
Hello! 


Sure thing, I should be able to push it with today's bugfix update :)

**Comment by Mordonus** [comment]
Done! (fece2de)

It should go live womewhen withing 24 hours :)

**Comment by Mordonus** [comment]
Update went to certification just now.
