### ISSUE TITLE
[request] Sorting options

### ISSUE THREAD

**Issue by Shinero** [Mordonus/MALClient#39]
Hello, thank you fort this app. Its the reason why I switched from AniDB to MAL, but could you please add another sorting option by "date added to my list"?

**Comment by Mordonus** [comment]
Hi! There's no such info provided by MAL, all I can do is to add sorting by start/end date which you can fill in either manually or enable setters in settings. Should be easy enough to appear in next update (after v4.3.124)

**Comment by Shinero** [comment]
I guess that will be sufficient. Thank you.

**Comment by Mordonus** [comment]
Done! I don't really know when this is going to go live as there's update already in certification since Friday...
