### ISSUE TITLE
Add volume count at manga when using MyAnimeList

### ISSUE THREAD

**Issue by Melvinkooi** [Mordonus/MALClient#40]
When using the manga list with MyAnimeList, you can only update chapters and not the volume count on manga. I would like to have this feature so i can also edit the volume count from the client as well.

**Comment by Mordonus** [comment]
You are right, I have volume data easily accessible but I didn't feel like doing UI for it for some reason. Expect it in update after v4.3.124.0 ^^

**Comment by Mordonus** [comment]
Done, you will be able to change which value is displayed on list items and used when incrementing/decrementing. Details page will have both values available to change. Should go live somewhen this week (certification takes awfully long lately) :)

**Comment by Melvinkooi** [comment]
Thanks! I don't see me going to replace chapters with volumes in my list view though. But otherwise it's all what i wanted.

**Comment by Mordonus** [comment]
Hah, tbh I don't really keep track of chapters and as I read mostly novels it is easier to input volumes. I can't really why I didn't implemented this earlier ^^
