### ISSUE TITLE
[Help me!]This page is atrocious... any ideas on how to improve the design?

### ISSUE THREAD

**Issue by Mordonus** [Mordonus/MALClient#46]
![image](https://cloud.githubusercontent.com/assets/6102530/17703983/c97e5200-63d3-11e6-9310-737e032866d4.png)

No further explanation required...

**Comment by ZeroOmar** [comment]
no need to make it populate the main body of the application. just but it in the side panel as if it's a normal settings page maybe call it "Login" in stead of "account" to be spotted easily

![screenshot 6](https://cloud.githubusercontent.com/assets/18592104/17707486/5474fdd6-63e9-11e6-9604-529ad01e363a.jpg)

**Comment by Kimod** [comment]
You could render top anime (or something different, maybe airing?) behind it. The grid would be able to scale to the screen of the user and I think that it doesn't look bad ^^ 
![concept](https://cloud.githubusercontent.com/assets/6088494/17707814/6965d0d2-63e2-11e6-9842-af67aee5eb02.png)

**Comment by Mordonus** [comment]
Wow, @Kimod 's solution looks pretty damn good... and pretty complicated.

As for @ZeroOmar 's idea... hmm... I could squeeze the log-in page there AND navigate to Top Anime on the main pane.

Now what's left is logo (*again*), I feel internal need to change it into something better...

**Comment by ZeroOmar** [comment]
an easy way to make Kmod's idea is to link the background to an auto generated anime tiles wallpaper like the masterani site used to do with some anime that doesn't have a cover image

**Comment by Mordonus** [comment]
PNG masterrace!

![image](https://cloud.githubusercontent.com/assets/6102530/17710212/94584e8c-63ec-11e6-90df-52020e00ea2f.png)

Much better "out of the box experience"

**Comment by Mordonus** [comment]
Mission complete... thanks!
