### ISSUE TITLE
[Question] Worried about mobile screen width.

### ISSUE THREAD

**Issue by Mordonus** [Mordonus/MALClient#5]
I'm testing this app on Lumia 640 (1280x720), but there are phones with smaller screen. How does it look on them? Is everything scaling properly or there's some odd clipping?

**Comment by ZeroOmar** [comment]
Here is how list and grid views look on lumia 630 (480x854) in both portrait and landscape modes
the only issue is the grid landscape mode shows 2 colums with an empty space to the right

![wp_ss_20160421_0001](https://cloud.githubusercontent.com/assets/18592104/14704063/2f5a259a-07b3-11e6-9908-3e669ec9337c.png)
![wp_ss_20160421_0002](https://cloud.githubusercontent.com/assets/18592104/14704064/2f85c498-07b3-11e6-9528-fa08f604c6c9.png)
![wp_ss_20160421_0003](https://cloud.githubusercontent.com/assets/18592104/14704065/2f98f00e-07b3-11e6-80c1-b8da5f9b048a.png)
![wp_ss_20160421_0004](https://cloud.githubusercontent.com/assets/18592104/14704066/2f9f75aa-07b3-11e6-9e26-8b3cd6d6b8f6.png)

**Comment by Mordonus** [comment]
Hello ,
ups , I totally forgot about this , should be easy enough to fix :)
Thanks for report!

**Comment by Mordonus** [comment]
![wp_ss_20160421_0002](https://cloud.githubusercontent.com/assets/6102530/14720253/e08b6cd2-0800-11e6-9f30-583eacd22ce1.png)

Done :)
