### ISSUE TITLE
No searches work

### ISSUE THREAD

**Issue by Insanitylious** [Mordonus/MALClient#8]
Searching for an anime or manga not in your list returns in a "No data received from MAL, try searching for something more specific. :(" error no matter what you search for.

**Comment by Mordonus** [comment]
That's very odd as I can search without an issue and there's no indication of this bug in other users' reviews....

Could you please try visiting this link : http://myanimelist.net/api/manga/search.xml?q=akame from your phone? (It'll ask for your password - it's official MAL api)

If it returns manga entries then the fault is on my end. MAL api is just *bad* and it returns invalid or no data from time to time so I want to be sure.

It should begin like this:
```
<manga>
<entry>
<id>11114</id>
<title>Akame</title>
<english/>
<synonyms>The Red Eyes</synonyms>
<chapters>2</chapters>
<volumes>1</volumes>
<score>7.51</score>
(...)
```

Sorry for inconvenience. :(

**Comment by Mordonus** [comment]
Resolved I guess...

**Comment by Insanitylious** [comment]
Sorry,  I just noticed you replied to this. Yes, it was an API error and it ia  resolved now :)

**Comment by DavidG72** [comment]
Hello,

I am having similar issue now...where no matter what title I search for it comes up with "we have come up empty" can someone help me with this?

David

**Comment by Drutol** [comment]
External service was down for a few hours.

**Comment by DavidG72** [comment]
Oh ok...thank you for the explanation.

David Glickman
